// add things that needed for each card here
export const boardBeforeRandomized = [
	{ value: 1, shown: true, flip: false },
	{ value: 1, shown: true, flip: false },
	{ value: 2, shown: true, flip: false },
	{ value: 2, shown: true, flip: false },
	{ value: 2, shown: true, flip: false },
	{ value: 2, shown: true, flip: false },
	{ value: 3, shown: true, flip: false },
	{ value: 3, shown: true, flip: false },
	{ value: 3, shown: true, flip: false },
	{ value: 3, shown: true, flip: false },
	{ value: 4, shown: true, flip: false },
	{ value: 4, shown: true, flip: false },
	{ value: 4, shown: true, flip: false },
	{ value: 4, shown: true, flip: false },
	{ value: 5, shown: true, flip: false },
	{ value: 5, shown: true, flip: false },
	{ value: 5, shown: true, flip: false },
	{ value: 5, shown: true, flip: false },
	{ value: 6, shown: true, flip: false },
	{ value: 6, shown: true, flip: false },
	{ value: 6, shown: true, flip: false },
	{ value: 6, shown: true, flip: false },
	{ value: 7, shown: true, flip: false },
	{ value: 7, shown: true, flip: false },
	{ value: 7, shown: true, flip: false },
	{ value: 7, shown: true, flip: false },
	{ value: "bomb", shown: true, flip: false },
	{ value: "bomb", shown: true, flip: false },
	{ value: "bomb", shown: true, flip: false },
	{ value: "bomb", shown: true, flip: false },
];
